name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.4
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: build with pyinstaller
        run: |
          cd src
          pip install -r requirements.txt
          pyinstaller --onefile MKS_WIFI_PS_upload.pyw
          ls -l dist/

      - uses: actions/upload-artifact@v2
        with:
          name: MKS_WIFI_PS_upload
          path: src/dist

      - name: Bump version and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ github.token }}
          dry_run: ${{ github.event_name == 'pull_request' && true || false }}

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ github.token }}
          base-ref: ${{steps.tag_version.outputs.previous_tag }}

      - name: Get the changelog
        shell: bash
        run: |
          cat << "EOF"
          ${{ steps.changelog.outputs.changelog }}
          EOF

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'push' }}
        with:
          name: ${{steps.tag_version.outputs.new_tag }}
          tag_name: ${{steps.tag_version.outputs.new_tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: src/dist/MKS_WIFI_PS_upload.exe
