name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: build with pyinstaller
      run: |
        cd src
        pyinstaller MKS_WIFI_PS_upload.pyw

    - uses: actions/upload-artifact@v2
      with:
        name: MKS_WIFI_PS_upload
        path: src/dist
